java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
problem: I replaced hamcrest-core inside junit to fix the issue Duplicate class org.hamcresDuplicate class org.hamcrest.BaseDescription, but forgot to implement hamcrest-core manually in other modules.

solve: implemented hamcrest-core manually in whatever module throwing the issue.